/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuleIdUnauthorizedRouteImport } from './routes/$moduleId/unauthorized'
import { Route as ModuleIdModuleLayoutRouteImport } from './routes/$moduleId/_moduleLayout'
import { Route as ModuleIdModuleLayoutIndexRouteImport } from './routes/$moduleId/_moduleLayout/index'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as ModuleIdModuleLayoutReviewRouteImport } from './routes/$moduleId/_moduleLayout/review'
import { Route as ModuleIdModuleLayoutNewVisaRouteImport } from './routes/$moduleId/_moduleLayout/new-visa'
import { Route as ModuleIdModuleLayoutInitializeRouteImport } from './routes/$moduleId/_moduleLayout/initialize'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleIdUnauthorizedRoute = ModuleIdUnauthorizedRouteImport.update({
  id: '/$moduleId/unauthorized',
  path: '/$moduleId/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleIdModuleLayoutRoute = ModuleIdModuleLayoutRouteImport.update({
  id: '/$moduleId/_moduleLayout',
  path: '/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleIdModuleLayoutIndexRoute =
  ModuleIdModuleLayoutIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ModuleIdModuleLayoutRoute,
  } as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleIdModuleLayoutReviewRoute =
  ModuleIdModuleLayoutReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => ModuleIdModuleLayoutRoute,
  } as any)
const ModuleIdModuleLayoutNewVisaRoute =
  ModuleIdModuleLayoutNewVisaRouteImport.update({
    id: '/new-visa',
    path: '/new-visa',
    getParentRoute: () => ModuleIdModuleLayoutRoute,
  } as any)
const ModuleIdModuleLayoutInitializeRoute =
  ModuleIdModuleLayoutInitializeRouteImport.update({
    id: '/initialize',
    path: '/initialize',
    getParentRoute: () => ModuleIdModuleLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$moduleId': typeof ModuleIdModuleLayoutRouteWithChildren
  '/$moduleId/unauthorized': typeof ModuleIdUnauthorizedRoute
  '/$moduleId/initialize': typeof ModuleIdModuleLayoutInitializeRoute
  '/$moduleId/new-visa': typeof ModuleIdModuleLayoutNewVisaRoute
  '/$moduleId/review': typeof ModuleIdModuleLayoutReviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$moduleId/': typeof ModuleIdModuleLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$moduleId/unauthorized': typeof ModuleIdUnauthorizedRoute
  '/$moduleId/initialize': typeof ModuleIdModuleLayoutInitializeRoute
  '/$moduleId/new-visa': typeof ModuleIdModuleLayoutNewVisaRoute
  '/$moduleId/review': typeof ModuleIdModuleLayoutReviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$moduleId': typeof ModuleIdModuleLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$moduleId/_moduleLayout': typeof ModuleIdModuleLayoutRouteWithChildren
  '/$moduleId/unauthorized': typeof ModuleIdUnauthorizedRoute
  '/$moduleId/_moduleLayout/initialize': typeof ModuleIdModuleLayoutInitializeRoute
  '/$moduleId/_moduleLayout/new-visa': typeof ModuleIdModuleLayoutNewVisaRoute
  '/$moduleId/_moduleLayout/review': typeof ModuleIdModuleLayoutReviewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/$moduleId/_moduleLayout/': typeof ModuleIdModuleLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$moduleId'
    | '/$moduleId/unauthorized'
    | '/$moduleId/initialize'
    | '/$moduleId/new-visa'
    | '/$moduleId/review'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$moduleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$moduleId/unauthorized'
    | '/$moduleId/initialize'
    | '/$moduleId/new-visa'
    | '/$moduleId/review'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$moduleId'
  id:
    | '__root__'
    | '/'
    | '/$moduleId/_moduleLayout'
    | '/$moduleId/unauthorized'
    | '/$moduleId/_moduleLayout/initialize'
    | '/$moduleId/_moduleLayout/new-visa'
    | '/$moduleId/_moduleLayout/review'
    | '/api/auth/$'
    | '/api/trpc/$'
    | '/$moduleId/_moduleLayout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ModuleIdModuleLayoutRoute: typeof ModuleIdModuleLayoutRouteWithChildren
  ModuleIdUnauthorizedRoute: typeof ModuleIdUnauthorizedRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$moduleId/unauthorized': {
      id: '/$moduleId/unauthorized'
      path: '/$moduleId/unauthorized'
      fullPath: '/$moduleId/unauthorized'
      preLoaderRoute: typeof ModuleIdUnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$moduleId/_moduleLayout': {
      id: '/$moduleId/_moduleLayout'
      path: '/$moduleId'
      fullPath: '/$moduleId'
      preLoaderRoute: typeof ModuleIdModuleLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$moduleId/_moduleLayout/': {
      id: '/$moduleId/_moduleLayout/'
      path: '/'
      fullPath: '/$moduleId/'
      preLoaderRoute: typeof ModuleIdModuleLayoutIndexRouteImport
      parentRoute: typeof ModuleIdModuleLayoutRoute
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$moduleId/_moduleLayout/review': {
      id: '/$moduleId/_moduleLayout/review'
      path: '/review'
      fullPath: '/$moduleId/review'
      preLoaderRoute: typeof ModuleIdModuleLayoutReviewRouteImport
      parentRoute: typeof ModuleIdModuleLayoutRoute
    }
    '/$moduleId/_moduleLayout/new-visa': {
      id: '/$moduleId/_moduleLayout/new-visa'
      path: '/new-visa'
      fullPath: '/$moduleId/new-visa'
      preLoaderRoute: typeof ModuleIdModuleLayoutNewVisaRouteImport
      parentRoute: typeof ModuleIdModuleLayoutRoute
    }
    '/$moduleId/_moduleLayout/initialize': {
      id: '/$moduleId/_moduleLayout/initialize'
      path: '/initialize'
      fullPath: '/$moduleId/initialize'
      preLoaderRoute: typeof ModuleIdModuleLayoutInitializeRouteImport
      parentRoute: typeof ModuleIdModuleLayoutRoute
    }
  }
}

interface ModuleIdModuleLayoutRouteChildren {
  ModuleIdModuleLayoutInitializeRoute: typeof ModuleIdModuleLayoutInitializeRoute
  ModuleIdModuleLayoutNewVisaRoute: typeof ModuleIdModuleLayoutNewVisaRoute
  ModuleIdModuleLayoutReviewRoute: typeof ModuleIdModuleLayoutReviewRoute
  ModuleIdModuleLayoutIndexRoute: typeof ModuleIdModuleLayoutIndexRoute
}

const ModuleIdModuleLayoutRouteChildren: ModuleIdModuleLayoutRouteChildren = {
  ModuleIdModuleLayoutInitializeRoute: ModuleIdModuleLayoutInitializeRoute,
  ModuleIdModuleLayoutNewVisaRoute: ModuleIdModuleLayoutNewVisaRoute,
  ModuleIdModuleLayoutReviewRoute: ModuleIdModuleLayoutReviewRoute,
  ModuleIdModuleLayoutIndexRoute: ModuleIdModuleLayoutIndexRoute,
}

const ModuleIdModuleLayoutRouteWithChildren =
  ModuleIdModuleLayoutRoute._addFileChildren(ModuleIdModuleLayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ModuleIdModuleLayoutRoute: ModuleIdModuleLayoutRouteWithChildren,
  ModuleIdUnauthorizedRoute: ModuleIdUnauthorizedRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
